name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: oven-sh/setup-bun@v1
    - run: sudo apt-get install brotli
    - run: sudo apt-get install gzip
    - run: sudo apt-get install zstd

    - run: bun install
    - run: bun run build

    - name: pre-compress (brotliBrotli)
      run: find static -type f -exec brotli --best --force --keep --output="{}.br" {} \;
    - name: pre-compress (gzip)
      run: find static -type f ! -name '*.br' ! -name '*.zst' -exec gzip --best --force --keep "{}" \;
    - name: pre-compress (zstd)
      run: find static -type f ! -name '*.br' ! -name '*.gz' -exec zstd --ultra -22 --keep "{}" \;




    - name: Commit and Push to Build Branch
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "The little robot inside Github.com"
        git checkout -b build
        git add -f --all
        git commit -m "Build files"
        git push origin build --force

